name = "freecell"
version = "1.2.2"

description = "FreeCell for the terminal"
licences = ["MIT"]
repository = { type = "github", user = "nerggnet", repo = "freecell" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
